resources:
  - name: git
    icon: github
    type: git
    source:
      uri: https://github.com/johnsen10/concoursepipelinedemo.git
      branch: main
  - name: image
    type: registry-image
    source:
      repository: ((image-name))
      username: ((registry-username))
      password : ((registry-password))
      tag: latest

jobs:
  - name: unit-test
    plan:
      - get: git
        version: latest # Just process the latest Git commit
        trigger: true
      - task: run-unit-tests
        file: git/ci/unit-test-task.yml
  - name: create-image-push
    plan:
      - get: git
        passed:
          - unit-test
        trigger: true
      - task: create-image
        file: git/ci/docker-image-create-task.yml
      - put: image
        params: {image: image/departementimg.tar}
